---
# Variables for containerd installation
docker_apt_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable"
docker_packages: 
  - docker-ce=5:19.03.13~3-0~ubuntu-focal
  - docker-ce-cli=5:19.03.13~3-0~ubuntu-focal
  - containerd.io=1.3.7-1
# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted