---
- name: Add an apt signing key for Docker
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: Add apt repository for stable version 
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install docker and its dependecies
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Hold docker version
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Docker Daemon config for Kubernetes
  template:
    src: "{{ docker_deamon_config_template }}"
    dest: "{{ docker_deamon_config_file }}"
  register: dockerdaemon
  when: kubernetes_role == 'master' or kubernetes_role == 'node'

- name: reload docker
  command: "service docker restart"
  when: dockerdaemon.changed

