---
# Variables for Kubernetes installation
kubernetes_version: '1.19.6'
kubernetes_service_cidr: "10.96.0.0/12"
kubernetes_pod_network_cidr: "10.10.0.0/16"
kubernetes_kubeadm_config: "/etc/kubernetes/admin.conf"
kubernetes_kubeadm_ca: "/etc/kubernetes/pki/ca.key"
kubernetes_kubelet_extra_args: ""
kubernetes_kubeadm_init_extra_opts: ""
#For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'
kubernetes_join_command_extra_opts: ""
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'
kubernetes_ignore_preflight_errors: 'all'
